-- Rode isso no SQL Editor do Supabase (New query → cole tudo → Run).
--
-- NADA A FAZER AQUI: este arquivo foi mantido só pela numeração.
-- As tabelas `permissions` e `access_requests`, o RLS e as policies
--   "permissions: self read only", "access_requests: self insert" e "access_requests: self read own"
-- são definidos UMA vez só, na 001_schema_inicial.sql. Antes, este arquivo repetia exatamente as mesmas
-- definições (era o "complemento" para quem tinha rodado uma versão antiga do schema sem essas tabelas),
-- e rodar 001 e depois 002 num banco novo falhava com "policy ... already exists".
--
-- Se o seu banco é de antes dessas tabelas, rode a 001 de novo: ela é idempotente e só cria o que falta.
